# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot1', models.CharField(max_length=35)),
                ('slot2', models.CharField(max_length=35)),
                ('slot3', models.CharField(max_length=35)),
                ('slot4', models.CharField(max_length=35)),
                ('slot5', models.CharField(max_length=35)),
            ],
        ),
    ]
